version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: echo_core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Initial1!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  helion-api:
    build:
      context: ./EchoCore
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
